; ==========================================
; ТРАНСПОРТ (Сетевые настройки)
; ==========================================
[transport-udp]
type=transport
protocol=udp
bind=172.16.0.145:5060

; ==========================================
; ШАБЛОН ДЛЯ ПОЛЬЗОВАТЕЛЕЙ (Экономит место)
; ==========================================
[endpoint-template](!)
type=endpoint
context=from-internal
disallow=all
allow=ulaw
allow=alaw
transport=transport-udp

; ==========================================
; ПОЛЬЗОВАТЕЛЬ: 101 (Для Linphone)
; ==========================================
[101](endpoint-template)
auth=auth101
aors=101

[auth101]
type=auth
auth_type=md5
username=101
; Пароль для регистрации в Linphone
password=SuperSecretPass101 

[101]
type=aor
max_contacts=1
remove_existing=yes ; Выбивать старую регистрацию при появлении новой

; ==========================================
; ПОЛЬЗОВАТЕЛЬ: 102 (Второй клиент)
; ==========================================
[102](endpoint-template)
auth=auth102
aors=102


[auth102]
type=auth
auth_type=md5
username=102
password=SuperSecretPass102 

[102]
type=aor
max_contacts=1
remove_existing=yes ; Выбивать старую регистрацию при появлении новой


[kamailio-trunk-identify]
type=identify
endpoint=kamailio-trunk
match=172.16.0.149

[kamailio-trunk]
type=endpoint
context=from-internal ; Контекст, где лежит ваш dialplan для "200"
allow=ulaw,alaw
auth=
; --- ДОБАВИТЬ ЭТИ СТРОКИ ДЛЯ ИСПРАВЛЕНИЯ ЗВУКА ---
;direct_media=no
;rtp_symmetric=yes
;force_rport=yes
;rewrite_contact=yes
;rtp_symmetric=yes — заставляет Asterisk слать RTP-звук ровно на тот IP и порт, с которого этот звук к нему прилетел от клиента. Это мгновенно лечит тишину в 99% случаев.direct_media=no — запрещает Asterisk пытаться перенаправлять звук между клиентами напрямую bypass-методом.
; --- ЖЕСТКИЕ НАСТРОЙКИ ДЛЯ ЧИНИКА ЗВУКА НА ЗАДВОЕННЫХ СЕТЯХ ---
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
direct_media=no
timers=off
; rtp_symmetric=yes и force_rport=yes — заставляют Asterisk отправлять RTP-звук строго на тот IP и UDP-порт, с которого baresip прислал свои первые медиа-пакеты. Это обходит любые проблемы с NAT и балансерами.
