[modules]
autoload=yes

; Запрещаем загрузку старых/ненужных драйверов каналов
noload => chan_alsa.so
noload => chan_console.so
noload => chan_sip.so

; Обязательно загружаем pjsip
load => res_pjsip.so
load => chan_pjsip.so
